### ISSUE TITLE
Stworzenie generycznego interfejsu lub klasy abstrakcyjnej operacji CRUD dla kontrolerów

### ISSUE THREAD

**Issue by KartVen** [skni-kod/KodemyBackend#25]
Zadanie polega na stworzeniu **interfejsu** lub **klasy abstrakcyjnej** deklarującej/ego podstawowe metody operacji CRUD do późniejszego użycia przy tworzeniu kontrolerów. W zadaniu należy użyć typów generycznych.

**Comment by OskarN8** [comment]
Closed #25
